version: "3"
services:
  cache:
    image: "redis:6"
    ports:
      - "6379:6379"
  load_balancer:
    image: "nginx:1"
    restart: "always"
    ports:
      - "9000:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "server"
  server:
    build: "./server"
    expose:
      - "9000"
    environment:
      REDIS_URI: "cache:6379"
